### ISSUE TITLE
Spawned on undeep water and cannot leave

### ISSUE THREAD

**Issue by mRmetr0** [TechnicJelle/CMGT-Project-Innovation#40]
![image](https://github.com/TechnicJelle/CMGT-Project-Innovation/assets/99254814/3111590d-4a4d-4f19-b840-89c2a90de131)

Ship cannot leave (what probably is) the islands solid hitbox when spawned on top of it.

**Comment by TechnicJelle** [comment]
This happens because there's a hole in the colliders:
![image](https://github.com/TechnicJelle/CMGT-Project-Innovation/assets/22576047/71064701-1569-4106-8c9b-9b8344defc5e)
![image](https://github.com/TechnicJelle/CMGT-Project-Innovation/assets/22576047/345d4ec8-082f-4a08-a433-d46d67997475)

**Comment by TechnicJelle** [comment]
Should be an easy fix

**Comment by mRmetr0** [comment]
Fixed in larger-island branch
