### ISSUE TITLE
In-game hud doens't remove old clients

### ISSUE THREAD

**Issue by mRmetr0** [TechnicJelle/CMGT-Project-Innovation#50]
![image](https://github.com/TechnicJelle/CMGT-Project-Innovation/assets/99254814/b7765545-5180-4a90-9348-52da1f7378bb)

I mannaged to create this image using 1 client.
By connecting one client, starting the game
Then pausing an quitting the game
(then if you want to, chance the clients name)
then starting the game again.
This does not get fixed when you exit the lobby screen -> title screen.

Image without doing anything client side, just quitting -> starting game.
![image](https://github.com/TechnicJelle/CMGT-Project-Innovation/assets/99254814/454dc0f8-f2b2-42b5-ac66-4fa4b06946a7)

Found in commit : 3eb6c36cb66a871206c48ddcffd02f6f6b4e18cf (I hope Im doing the linking right)

**Comment by TechnicJelle** [comment]
Oh yeah, now that you mention it, I think I may have indeed forgotten to make the Boats remove their entry in the list when they're removed from the game.
Or I could just wipe the list when the game starts.. 🤔
I'll look into it!
